### ISSUE TITLE
dot test passes in assert only if using .data for viscoacoutic case (PR #95)

### ISSUE THREAD

**Issue by nogueirapeterson** [slimgroup/JUDI.jl#104]
Hi guys,

In our PR #95, we found an issue with respect `dot` function. We noticed that the `dot` test only passes in assert when we use `.data` in the input argument. 

Attached is an MFE [mfe.txt](https://github.com/slimgroup/JUDI.jl/files/8490297/mfe.txt).
Run with:
`julia mfe.jl --viscoacoustic`

**Comment by mloubout** [comment]
As francis pointed out, object are dimensionalized. This is related to this comment on your PR:

https://github.com/slimgroup/JUDI.jl/pull/95/files#r845700881

The gradient is accumulated with a dimensionalized discrete intergral that needs the `dt` so you need to use the `w` like for the other cases and then you should not need the `.data`

**Comment by nogueirapeterson** [comment]
@ziyiyin97 and @mloubout thank you for the explanation. Now the test works without the `.data`.

**Comment by mloubout** [comment]
Great closing
