### ISSUE TITLE
parallel problem when running on multi node

### ISSUE THREAD

**Issue by WYJLCYWHZ** [slimgroup/JUDI.jl#108]
Hi, I am new to parallel computing and I guess my situation is interesting for others, at least in terms of education. I try to run "[JUDI.jl](/examples/compressive_splsrtm/Sigsbee2A/rtm_sigsbee.jl" example on the cluster using 6 nodes，each contains 16 cores. I use PBS to submit my commands, but seem like parallel computing is not happening. Only one node (node16) is assigned to the task of parallel computing.
![16](https://user-images.githubusercontent.com/18225941/164730877-33ad6cc7-ef6e-4110-a506-0d1e97f71dff.png)

While other nodes are not assigned to the task.
![1](https://user-images.githubusercontent.com/18225941/164731071-49eeebd3-d993-4eaa-8e49-11378e9ffc7f.png)

Is there anything else I lose? Thank you very much.(*^▽^*)

**Comment by mloubout** [comment]
How are you submitting the job? If you are using PBS you should be using Julia's PBS ClusterManager, i.e check https://github.com/JuliaParallel/ClusterManagers.jl

If you don't then julia isn't aware of your PBS setup, only the node on which the program is executed so it won't make use  of the parallel resources.

**Comment by WYJLCYWHZ** [comment]
> How are you submitting the job? If you are using PBS you should be using Julia's PBS ClusterManager, i.e check https://github.com/JuliaParallel/ClusterManagers.jl
> 
> If you don't then julia isn't aware of your PBS setup, only the node on which the program is executed so it won't make use of the parallel resources.

Oh!  Sorry, I missed this setting. Thank you for your answer. (*^▽^*)

**Comment by WYJLCYWHZ** [comment]
Hi, Do you have an example of submitting tasks using ClusterManagers? Looks like I haven't been able to run him successfully.
