### ISSUE TITLE
LoadError: MethodError: no method matching Model(::Tuple{Int64, Int64}, ::Tuple{Float64, Float64}, ::Tuple{Int64, Int64}

### ISSUE THREAD

**Issue by WYJLCYWHZ** [slimgroup/JUDI.jl#119]
Hi, I am getting an error while running the example program in examples/compressive_splsrtm/Sigsbee2A/rtm_sigsbee.jl

ERROR: LoadError: MethodError: no method matching Model(::Tuple{Int64, Int64}, ::Tuple{Float64, Float64}, ::Tuple{Int64, Int64}, ::Matr
Closest candidates are:
  Model(::Any, ::Any, ::Any, ::Any, ::Any) at ~/.julia/packages/JUDI/Xrqx6/src/TimeModeling/Types/ModelStructure.jl:267
  Model(::Union{Vector{Int32}, Vector{Int64}, Tuple{Integer, Integer}, Tuple{Integer, Integer, Integer}}, ::Union{Tuple{AbstractFloat, ctor{AbstractFloat}}, ::Union{Tuple{AbstractFloat, AbstractFloat}, Tuple{AbstractFloat, AbstractFloat, AbstractFloat}, Vector{AbstractFckages/JUDI/Xrqx6/src/TimeModeling/Types/ModelStructure.jl:277
  Model(::Union{Vector{Int32}, Vector{Int64}, Tuple{Integer, Integer}, Tuple{Integer, Integer, Integer}}, ::Union{Tuple{AbstractFloat, ctor{AbstractFloat}}, ::Union{Tuple{AbstractFloat, AbstractFloat}, Tuple{AbstractFloat, AbstractFloat, AbstractFloat}, Vector{AbstractFling/Types/ModelStructure.jl:289

  ..
Stacktrace:
 [1] top-level scope
   @ ~/.julia/environments/v1.7/rtm_sigsbee.jl:13
in expression starting at /public/home/user/.julia/environments/v1.7/rtm_sigsbee.jl:13

It looks like the error is caused by a version update. Because there was no error in the previous version.

The current version is julia1.7+JUDI3.0.2, the previous version is julia1.4+JUDI3.0.0.

Do you have any suggestion for me. thank you.(*^▽^*)

**Comment by mloubout** [comment]
looks like some type constraint (expecxt float for origin) gives me ~1h will open PR for fix. In the mean time `Float32.(M["o"])` should fix it

**Comment by mloubout** [comment]
I haven't used PBS to run parallel julia so I am afraid I won't be of much help. There seem to be a small explanation here

https://github.com/juliohm/julia-distributed-computing

which seems to says that you need a standard PBS machine file and call julia with it. Then you can use `addprocs_pbs` in your code..
