### ISSUE TITLE
ERROR: LoadError: MethodError: no method matching SlimOptim.BregmanParams

### ISSUE THREAD

**Issue by AMzaheri** [slimgroup/JUDI.jl#121]
Hello,

I've tried denoising example from:
https://slimgroup.github.io/SlimOptim.jl/dev/tutorials/01_denoising/

With BergmanParams specified, it produces the following error:

ERROR: LoadError: MethodError: no method matching SlimOptim.BregmanParams(::Int64, ::Float64, ::Int64, ::Bool, ::Bool, ::Float64)
Closest candidates are:
  SlimOptim.BregmanParams(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at ~/.julia/packages/SlimOptim/rFROp/src/bregman.jl:5

I've tried opt = SlimOptim.BregmanParams(1, 1e-6, 1e-8, 20, false, .5, .25, false) as well,
 but the same error is produced.

Without specifying the parameter option though, it works.

I was wondering if you could advise me how to solve this issue.

Thank you,

**Comment by mloubout** [comment]
Please open the issue in the repository it belongs to.

**Comment by ziyiyin97** [comment]
Hi you should run

```julia
opt = bregman_options(maxIter=200, verbose=2, quantile=.1)
```

to define a BregmanParams instead of 

```julia
SlimOptim.BregmanParams(2, 1.0e-8, 200, false, true, 0.1)
```

**Comment by AMzaheri** [comment]
Great.  Thank you very much for your help and sorry for issuing in the wrong repository.
