### ISSUE TITLE
Unsatisfiable requirements detected for package SegyIO

### ISSUE THREAD

**Issue by aananaya** [slimgroup/JUDI.jl#15]
ERROR: Unsatisfiable requirements detected for package SegyIO [157a0f19]:
 SegyIO [157a0f19] log:
 ├─SegyIO [157a0f19] has no known versions!
 └─restricted to versions * by JUDI [f3b833dc] — no versions left
   └─JUDI [f3b833dc] log:
     ├─possible versions are: 1.2.3 or uninstalled
     └─JUDI [f3b833dc] is fixed to version 1.2.3

**Comment by philippwitte** [comment]
This looks like an issue with the Julia package manager, which according to Julia is not 100 percent worked out yet. You can try to remove the packages and reinstall:

1. Start an interactive Julia session and enable the package manager by typing `]`

2. Once in the package manager, type:

`rm JOLI, SegyIO, JUDI`
`resolve`

3. Hard delete any remaining files. Open a regular terminal and remove the following files:

`rm -rf ~/.julia/dev/JUDI`
`rm -rf ~/.julia/dev/JOLI`
`rm -rf ~/.julia/dev/SegyIO`

4. Follow the installation instructions from JUDI (run from a regular terminal):

`julia -e 'using Pkg; Pkg.clone("https://github.com/slimgroup/SegyIO.jl.git")'`
`julia -e 'using Pkg; Pkg.clone("https://github.com/slimgroup/JOLI.jl.git")'`

`julia -e 'using Pkg; Pkg.clone("https://github.com/slimgroup/JUDI.jl")'`
`pip install --user -r ~/.julia/dev/JUDI/docker/devito_requirements.txt`

`export PYTHON=$(which python)`
`julia -e 'using Pkg; Pkg.build("PyCall")'`

**Comment by philippwitte** [comment]
Julia still has some issues with caching and proper management of package dependencies, which sometimes results in the error you ran into. Very sorry about that and we're working on resolving this issue. Let me know if it still doesn't work. 
Many thanks,
Philipp

**Comment by aananaya** [comment]
Thank you Philipp, before SegyIO I have to add SeisIO.
