### ISSUE TITLE
UndefVarError: backtracking_linesearch not defined

### ISSUE THREAD

**Issue by kerim371** [slimgroup/JUDI.jl#159]
Hi,

Where `backtracking_linesearch` function is defined? I've found it used by some JUDI's [examples](https://github.com/slimgroup/JUDI.jl/blob/fbb2168487730f74020baa0f9a70d604197f8a46/examples/software_paper/fwi_2D_overthrust_sgd.jl#L87).

**Comment by mloubout** [comment]
Hi

These are indeed older example that I haven't updated since there were linked to a paper with a specific version of JUDI

You can find an modern example of like search here

https://github.com/slimgroup/JUDI.jl/blob/master/examples/scripts/fwi_example_constraints.jl
