### ISSUE TITLE
ERROR: UndefVarError: SLIM_optim not defined

### ISSUE THREAD

**Issue by zhangxiaoshuotttt** [slimgroup/JUDI.jl#174]
I have checked the issue "JUDI.SLIM_optim #6".I tried to do it according to  that issue, but it doesn"t seem to work.Here is what I did.

System            : Ubuntu 22.04
Julia version    : Julia1.6.7
Devito version : 4.8.0
`conda activate FWI` (The environment FWI has a Devito, its version is 4.8.0)
``ENV["PYTHON"]="/home/master/anaconda3/envs/FWI/bin/python"
$` JULIA`
`pkg.add("JUDI")`
I also tried `Pkg.add(PackageSpec(url="https://github.com/slimgroup/JUDI.jl"))`
`using JUDI` (No error)
`using JUDI.SLIM_optim `  then 
```
ERROR: 
UndefVarError: SLIM_optim not defined
```
Meanwghile,I try to run "Setup.sh",but it gives me an error saying I don't have  "docker/devito_requirements.txt"

This problem has bothered me for four days. I tried to find a solution,but since I just learned Julia, I couldn't find the problem .Please help me.

**Comment by ziyiyin97** [comment]
Hi, thanks for your interest in JUDI package. We've restructured the package a while ago (see #43 ) and `SLIM_optim` module is currently under https://github.com/slimgroup/SlimOptim.jl. We suggest you install that package and do `using SlimOptim` instead.

**Comment by ziyiyin97** [comment]
I've checked the `Setup.sh` file. It seems to be deprecated @mloubout correct me if wrong

**Comment by zhangxiaoshuotttt** [comment]
Thank you for your help. Thank you for your efforts.

**Comment by mloubout** [comment]
- `setup.sh` is deprecated and only kept for legacy. for early versions of JUDI
- `SLIM_optim` has been deprecated and is now its own package `SlimOptim.jl` 

You can check the example scripts such as :

https://github.com/slimgroup/JUDI.jl/blob/master/examples/scripts/fwi_example_minConf.jl

for usage

**Comment by zhangxiaoshuotttt** [comment]
> * `setup.sh` is deprecated and only kept for legacy. for early versions of JUDI
> * `SLIM_optim` has been deprecated and is now its own package `SlimOptim.jl`
> 
> You can check the example scripts such as :
> 
> https://github.com/slimgroup/JUDI.jl/blob/master/examples/scripts/fwi_example_minConf.jl
> 
> for usage

Ok, I'll check. Thanks a lot.
