### ISSUE TITLE
Modeling LSRTM - Devito tutorial

### ISSUE THREAD

**Issue by jddorellanao** [slimgroup/JUDI.jl#180]
Hi,

I tried to replicate this [Devito LSRTM](https://github.com/devitocodes/devito/blob/master/examples/seismic/tutorials/13_LSRTM_acoustic.ipynb) in JUDI, so far I've done [this](https://github.com/jddorellanao/miscellaneous/blob/main/T_j_lsrtm.ipynb). I'm having problems with the results, I'm 100% sure it's my coding for mixing these two references ([1](https://slimgroup.github.io/JUDI.jl/dev/tutorials/07_quickstart/), [2](https://slimgroup.github.io/JUDI.jl/dev/inversion/)) I am a newbie in JUDI.

The difference in amplitudes between the RTM image and the LSRTM image is huge. For the RTM I use:

```
imshow(diff(rtm.data, dims=2)', cmap="Greys", extent=[0, (n[1]-1)*d[1], (n[2]-1)*d[2], 0], vmin=-1e3, vmax=1e3)
```

Meanwhile for the LSRTM I use: 
```
imshow(diff(x.data, dims=2)', cmap="Greys", extent=[0, (n[1]-1)*d[1], (n[2]-1)*d[2], 0 ], , vmin=-0.05, vmax=0.05)
```

In the last figure I had to divide the RTM matrix by `1e4` to make the three lines somehow in the same range for the horizontal axis.

Thank you!

**Comment by mloubout** [comment]
That's normal and always the case. RTM doesn't have physical amplitudes so it is expected to have different scaling, LSRTM main goal is to go to physical amplitudes.
