### ISSUE TITLE
Error creating Born linearized data

### ISSUE THREAD

**Issue by jddorellanao** [slimgroup/JUDI.jl#192]
I just updated JUDI (3.2.3 -> 3.3.5) and ran into a problem when creating the Born linearized data. I leave the notebooks for the two versions and where is the error.

[JUDI 3.2.3](https://github.com/jddorellanao/miscellaneous/blob/main/judi/JUDIv3.2.3.ipynb)

[JUDI 3.3.5](https://github.com/jddorellanao/miscellaneous/blob/main/judi/JUDIv3.3.5.ipynb)

**Comment by mloubout** [comment]
You shouldn't need `vec` at all here the difference is a PhysicalParameter which is valid domain for J.

**Comment by Nat253** [comment]
Nat
