### ISSUE TITLE
Option to disable reflections from the bottom of the model

### ISSUE THREAD

**Issue by kerim371** [slimgroup/JUDI.jl#196]
Let's suppose the registration time is big enough to waves to reach the bottom of the model. In such case waves reflect from the bottom of the model and such waves appear on the seismogram. 
Is there a way to disable reflections from the bottom of a model?

**Comment by mloubout** [comment]
There is an abosrbing layer at the bottom of the layer however depending on the velocity there and how smooth your model is it might not be perfect so you can either increase the size of the boundary layer (`Model(... ; nb = )`). Other option is to design a new boundary condition for the bottom of the model

**Comment by kerim371** [comment]
That should help.
Thank you for explanation
