### ISSUE TITLE
sim source experiment

### ISSUE THREAD

**Issue by jddorellanao** [slimgroup/JUDI.jl#208]
Hi everyone,

I am trying to replicate the sim source experiment from the [documentation](https://github.com/slimgroup/JUDI.jl/blob/master/examples/software_paper/model_sim_sources.jl), so far this is my [code](https://github.com/jddorellanao/miscellaneous/blob/main/sim_source.ipynb). The problem I have encountered is that it takes too long (~60 min) and I don't even get any results. For comparison, I have run the same experiment without the sim source and it takes about 5 seconds to get the shot records, so is there something wrong with my code or is it normal that it takes so long?

**Comment by mloubout** [comment]
Hi

It should take the same time (5s) with sim source so something is off. Will have a look at your code.

**Comment by mloubout** [comment]
Your wavelet for the sim-source part is a `Float64`  array instead of a `Float32` which currently leads to some overflow due to type mismatch. if you make it `Float32` then it'll be fine

**Comment by jddorellanao** [comment]
Thanks a lot @mloubout
