### ISSUE TITLE
Elaxtic example `modeling_basic_elastic.jl` doesn't work

### ISSUE THREAD

**Issue by kerim371** [slimgroup/JUDI.jl#215]
Hi,

I tried to calculate forwad modeling using [modeling_basic_elastic.jl](https://github.com/slimgroup/JUDI.jl/blob/master/examples/scripts/modeling_basic_elastic.jl) script and found that it produces `NAN` values, i.e. `dobs.data[1] .== NAN`.

JUDI `v3.3.8`

**Comment by mloubout** [comment]
Oh ok thanks for noticing something must have changed will have a look

**Comment by mloubout** [comment]
Looks like cfl bound was a bit too tight, pushed a fix
