### ISSUE TITLE
Describe Wavefield Attenuation Not At Absorbing PML Regions

### ISSUE THREAD

**Issue by tjk9501** [slimgroup/JUDI.jl#219]
Hello,

In simulations I input some laboratory sampled signals as source data. However, even if I carefully deploy the transducers to make sure they do not located at predefined PML boundary region. The amplitude of sampled signals at receivers seems significantly reduced compared to source data. Here I presented the waveform of source data, which is a 16 cycled sinusodial pulse.
![SourcePulse](https://github.com/slimgroup/JUDI.jl/assets/54341310/a99ca655-2396-4fa9-8964-f737192df7af)
The received data, which propagated in a homogeneous medium several meters away from the source, lookes like this
![DevitoFWISimul](https://github.com/slimgroup/JUDI.jl/assets/54341310/25c87c7a-3680-4185-b992-0fb1ec4292d3)
If no attenuation is presented, I assume the pulse might correspond to the analytical expression of Hann windowed  sinusodial pulse, and it looks like
![HannWindowedSimul](https://github.com/slimgroup/JUDI.jl/assets/54341310/e03de2eb-7921-44ff-af0a-3c4d830f6e02)

Why is attenuation occured? I wonder what causes the amplitude difference between finite difference modeling and analytical expression of pulse, and how to compensate this effect in the analytical expression?

Thanks!

**Comment by mloubout** [comment]
There is no attenuation here, this is the expected propagation effect which is in 2D the convolution of your source with a Hankel function. The energy is preserved in the isotropic acoustic case which means the energy of "25" of your source at a single point is distributed over all space after propagation.

You can see a more detailed overview of 2D propagation effects for a ricker wavelt here:

https://nbviewer.org/github/devitocodes/devito/blob/master/examples/seismic/acoustic/accuracy.ipynb

A simple rule of thumb is that the amplitude follow spherical spreading for a point source which means at time `t` the amplitude is reduced by `1/sqrt(t)` in 2D and `1/t` in 3D

**Comment by tjk9501** [comment]
Thank you for your generous and detailed explanation!
