### ISSUE TITLE
Function name incorrect in FWI example in README

### ISSUE THREAD

**Issue by advaitb** [slimgroup/JUDI.jl#223]
The line `x, fsave, funEvals= minConf_SPG(objective_function, vec(m0), ProjBound, options)` throws an error because the function doesn't exist in SlimOptim, should probably be replaced by `x, fsave, funEvals= spg(objective_function, vec(m0), ProjBound, options)`

**Comment by mloubout** [comment]
Missed this one indeed, thank you for catching it, fixed.
