### ISSUE TITLE
Optimal checkpointing

### ISSUE THREAD

**Issue by kerim371** [slimgroup/JUDI.jl#261]
Hi,

I'm trying to use `optimal_checkpointing` to save memory.
As I understand this option is aimed to recompute wavefields instead of keeping them in RAM or on the hardware.

It seems that when I use this option my RAM memory is loaded only for 5-10% and the computations run about 10 times longer.
Is it really optimized? Is there a way to control how much checkpoints is used or huw much memory is used during computations?

![image](https://github.com/slimgroup/JUDI.jl/assets/43808863/b9f4db22-4f0b-4e3f-8522-5dec9c93efbd)

**Comment by mloubout** [comment]
It is fairly optimized yes but it will take longer by a bit. There is some option in `pyrevolve` to control the memory but it's a bit of a pain to expose it to the user

**Comment by kerim371** [comment]
It seems I can change [n_checkpoints directly in J_adjoint in source code](https://github.com/slimgroup/JUDI.jl/blob/adcb13a679543ee2c68de012608bd4cc1f2dfe8f/src/pysource/interface.py#L331). 
As I understand it should work faster if `n_checkpoints` is big enough. Also if `n_checkpoints == nt_comp` then the perfomance should be almost equal when `JUDIOptions::optimal_checkpointing = false` right?

**Comment by mloubout** [comment]
>  if n_checkpoints == nt_comp ..

Well in theory yes, but  no it will have a lot of overhead going back and forth wit the checkpointing backend so it'll still be slower.
