### ISSUE TITLE
3D Overthrust.h5 file

### ISSUE THREAD

**Issue by CozyHUA** [slimgroup/JUDI.jl#273]
Could you provide the data "ftp://slim.gatech.edu/data/SoftwareRelease/WaveformInversion.jl/3DFWI/overthrust_3D_true_model.h5"? It is very signifiant for us to apply our new approach into 3D Overthrust velocity model

**Comment by mloubout** [comment]
- ftp://slim.gatech.edu is currently down and we are working on getting it back up
- The overthrust model is also publicly available on the SEG website https://wiki.seg.org/wiki/SEG/EAGE_Salt_and_Overthrust_Models
