### ISSUE TITLE
True model not found

### ISSUE THREAD

**Issue by cako** [slimgroup/JUDI.jl#3]
I have been trying to reproduce the figures in the README, but I cannot find the true model. Would this be something which can be added to the repository? Maybe in the data folder? Cheers!

**Comment by philippwitte** [comment]
Hi Carlos, 
you don't need the true model to run the experiment, as you can pull the observed data from the FTP server. I added the true model to the server anyway, in case you want to compare the results to the true model or generated your own data. I updated the README and the true model in squared slowness isnow in the variable `m`.

**Comment by cako** [comment]
Excellent, many thanks!
