### ISSUE TITLE
Mpi problem when running on cluster?

### ISSUE THREAD

**Issue by mlin26** [slimgroup/JUDI.jl#32]
Hi,

I try to run "examples/scripts/modeling_basic_3D.jl" example on the cluster using 8 cores, but I got some warnings, shown in the following picture: 
![image](https://user-images.githubusercontent.com/48300409/90216617-46d25100-ddbc-11ea-9bbb-c990273f775d.png)

On the cluster, I allocate the resource using: ``` salloc --nodes 2  --ntasks-per-node 4 -t 1:00:00 --mem-per-cpu 25G ``` and then run julia interactively.  There is no warning or error when I run this script on my local workstation using 8 cores. 

And I've got some errors when running 3D modeling and inversion using my own examples. The model is quite simple:
![image](https://user-images.githubusercontent.com/48300409/90222914-40e36c80-ddca-11ea-9255-f39f7c0c8819.png)
In this example, I use 64 cores on cluster:  ``` salloc --nodes 16  --ntasks-per-node 4 -t 1:00:00 --mem-per-cpu 25G ```. 
![image](https://user-images.githubusercontent.com/48300409/90224524-07f8c700-ddcd-11ea-9947-c520da0a8985.png)

But I got no errors when I ran the scripts using 8 cores in both modeling and inversion: ``` salloc --nodes 2  --ntasks-per-node 4 -t 1:00:00 --mem-per-cpu 25G ```. And I also can run on my local workstation using 8 cores.

I've tried to solve this problem online for several days, but not find a solution. Could you tell me where might be wrong? Thanks!

**Comment by mloubout** [comment]
Hi.

First question, "MPI problem". Do you run something with MPI? 

> but I got some warnings, shown in the following picture:

These warnings says that you only have an old version of gcc (<4.9) installed that doesn't support openMP. You will need a newer version and the warning will disappear.

>And I've got some errors when running 3D modeling and inversion using my own examples.

Any info on what code it is and how you run it. `BUS ERROR` means there is a memory issue somewhere and the program crashed.

**Comment by mlin26** [comment]
Thanks for your response. 

> First question, "MPI problem". Do you run something with MPI?

I mean openmp instead of mpi. Sorry for the confusion.

> These warnings says that you only have an old version of gcc (<4.9) installed that doesn't support openMP. You will need a newer version and the warning will disappear.

After I change gcc to 7.3.0, it still has the warnings. 

> Any info on what code it is and how you run it. BUS ERROR means there is a memory issue somewhere and the program crashed.

Here are two files for modeling and gradient computation.
[Min_modeling_3D.jl.txt](https://github.com/slimgroup/JUDI.jl/files/5076748/Min_modeling_3D.jl.txt)
[Min_gradient_3D.jl.txt](https://github.com/slimgroup/JUDI.jl/files/5076750/Min_gradient_3D.jl.txt)

First, I ran "Min_modeling_3D" to get the shot data files saved in "Min_3D.segy". I was able to run "Min_modeling_3D.jl" on both cluster (2 nodes, 4 cpus per node, total 8 cores) and my workstation (8 cores). Then, I ran "Min_gradient_3D.jl" on the cluster to calculate the gradient. But when I run the "Min_gradient_3D.jl" using sbatch (2 nodes, 32 cpus per node, total 64 cores), it showed both warnings and bus errors. The warning still exists when I change gcc to 7.3.0. The log file is:

[slurm-9374384.out.txt](https://github.com/slimgroup/JUDI.jl/files/5076802/slurm-9374384.out.txt)

The sbatch script that I use to run "Min_gradient_3D.jl"  is shown in the following:
```#SBATCH --job-name=3D_Gradient
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=120G
#SBATCH --time=0-20:00:00

module load gcc/7.3.0
julia Min_gradient_3D.jl
``` 
The memory for each node is 120G. I don't know if this is enough for fwi. But this is the maxium that can allocate on my cluster.

Let me know if I need to provide more information. Thanks a lot!

**Comment by mloubout** [comment]
Bus errors usually come from out of memory issues. I'll g=have a look but looks like should fit in memory I think

**Comment by mloubout** [comment]
If it works fine with 2 nodes but not 16, it is probably an issue with the cluster setup or maybe you have more resources on a single node than expected.

**Comment by mlin26** [comment]
Could you tell me how I can make the cluster setup correct? Does anything in my sbatch file need to change? It seems that there are some communication issues between these nodes.

**Comment by mloubout** [comment]
Is this issue still happening?

**Comment by mloubout** [comment]
Closing since stale. Will reopen if needed.
