### ISSUE TITLE
Assembler Message

### ISSUE THREAD

**Issue by ziyiyin97** [slimgroup/JUDI.jl#37]
Hi,

I was running an LS-RTM (101 sources, 401 receivers, BG model, batchsize 8) and the code is here [https://github.gatech.edu/zyin62/multiples/blob/master/BG_multiple.jl](url). I got a warning in the 2nd iteration (but no warning afterwards). The warning is in assembly level which I am not good at interpreting. Could you please help me check if this is OK?

Thanks

```
From worker 2:	/tmp/ccNEhkjv.s: Assembler messages:
From worker 2:	/tmp/ccNEhkjv.s:2262: Warning: index and destination registers should be distinct
From worker 2:	/tmp/ccNEhkjv.s:2794: Warning: index and destination registers should be distinct
```

**Comment by mloubout** [comment]
That's definitely not a JUDI error, we don;t touch these.
