### ISSUE TITLE
Incorrect seismograms from JudiModeling

### ISSUE THREAD

**Issue by rodrigofeliciof** [slimgroup/JUDI.jl#42]
Hello I am getting a strange result when trying to compute a shot gather with traces that are 10s long. Looks like there is an issue with padding somewhere, but being brand new to JUDI (and devito) I am really not sure what is going on. With Devito only I can compute the seismograms without an issue, so I am wondering what is it that I am doing wrong here.  A minimal example follows:

```
using PyPlot, HDF5, SegyIO, JUDI.TimeModeling, JUDI.SLIM_optim, Statistics, Random, LinearAlgebra

# Load smooth migration velocity model
n,d,o,m0 = read(h5open("marmousi_migration_velocity.h5","r"), "n", "d", "o", "m0")
model0 = Model((n[1],n[2]), (d[1],d[2]), (o[1],o[2]), m0)

#Set up source geometry
nsrc = 1  # no. of sources
xsrc = convertToCell(range(800*5f0, stop=800*5f0, length=nsrc))
ysrc = convertToCell(range(0f0, stop=0f0, length=nsrc))
zsrc = convertToCell(range(20f0, stop=20f0, length=nsrc))

# Modeling time and sampling interval
time = 10000f0  # ms
dt = 4f0   # ms

# Set up source structure
src_geometry = Geometry(xsrc, ysrc, zsrc; dt=dt, t=time)

# Source wavelet
f0 = 0.010f0     # kHz
wavelet = ricker_wavelet(time, dt, f0)
q = judiVector(src_geometry, wavelet);

# Set up receiver geometry (for 2D, set yrec to zero)
nxrec = 101
xrec = range(0f0, stop=1599*5f0, length=nxrec)
yrec = 0f0
zrec = range(50f0, stop=50f0, length=nxrec)

# Set up receiver structure
rec_geometry = Geometry(xrec, yrec, zrec; dt=dt, t=time, nsrc=nsrc);

# Set up info structure for linear operators
ntComp = get_computational_nt(src_geometry, rec_geometry, model0)
info = Info(prod(n), nsrc, ntComp)

#Setup operators
Pr = judiProjection(info, rec_geometry)
A_inv = judiModeling(info, model0)
Ps = judiProjection(info, src_geometry);

F = judiModeling(info, model0, src_geometry, rec_geometry);
F = Pr*A_inv*Ps';
d_obs = F*q
```

The shot gather, however, has this really strange low freq signal at the bottom of the traces 

```
pcolormesh(d_obs.data[1], vmin=-1, vmax=1, cmap="seismic")
gca().invert_yaxis()
```
![shotgather_juliatest](https://user-images.githubusercontent.com/24499097/99418510-b88cd000-28c0-11eb-90ea-a013167f72b8.png)

```
plot(d_obs.data[1][1:4:end,51], "r.-")
```

![shotgather_juliatest_trace](https://user-images.githubusercontent.com/24499097/99418551-c3dffb80-28c0-11eb-87fb-a6f8e9aa7353.png)

**Comment by ziyiyin97** [comment]
Message from Dr. Felix J. Herrmann:

Most likely you did something wrong w/ CFL conditions etc. Check https://github.com/slimgroup/JUDI.jl/blob/master/examples/software_paper/examples/generate_data_marmousi_2D.jl for comparison.

**Comment by mloubout** [comment]
Thanks for letting us know, I will look into it. My understanding is that this appear for very long recording times (like your 10sec) when the frequency is very low compared to the grid spacing. I will see if I can make the modeling more robust to these variations.

**Comment by mloubout** [comment]
You can do 
```
#Setup operators
opt = Options(dt_comp=.4)
Pr = judiProjection(info, rec_geometry)
A_inv = judiModeling(info, model0; options=opt)
Ps = judiProjection(info, src_geometry);
```

In the mean time, it should help

**Comment by rodrigofeliciof** [comment]
Thanks for the prompt answers and help, @mloubout! Very handy to know how to override the default settings for the time-step. BTW, it seems that somehow the time-step is rounded up inside `judiModeling`, because  with `dt_comp=10s/ntComp $\approx$ 0.446`, I  get the result shown on the figure below, while `dt_comp=0.5` outputs the result I posted before

![shotgather_juliatest_corr](https://user-images.githubusercontent.com/24499097/99444819-55ac3080-28e2-11eb-99d8-b6a51e82ba5e.png)

**Comment by mloubout** [comment]
Glad it fixes it for you, closing the issue (will be fixed in the default in next version)
