### ISSUE TITLE
Example from repository main page doesn't work

### ISSUE THREAD

**Issue by kerim371** [slimgroup/JUDI.jl#45]
Hi,

I'm trying to run the [example](https://github.com/slimgroup/JUDI.jl#full-waveform-inversion) from main repository page and I get the error:
```
MethodError: no method matching minConf_SPG(::typeof(objective_function), ::PhysicalParameter{Float32}, ::typeof(ProjBound), ::JUDI.SLIM_optim.SPG_params)
Closest candidates are:
  minConf_SPG(::Any, !Matched::Array{vDt,N} where N, ::Any, ::Any) where vDt at /root/.julia/dev/JUDI/src/Optimization/SPGSlim.jl:78

Stacktrace:
 [1] top-level scope at In[6]:25
 [2] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091
```
at the very last line:
```jl
x, fsave, funEvals= minConf_SPG(objective_function, vec(model0.m), ProjBound, options)
```

I don't have GPU computing on my computer that is why I created [Colab notebook](https://github.com/kerim371/Julia-Devito-Inversion-JUDI-examples-in-Colab) with that example and it allows me to launch the code on the cloud. It uses Julia 1.5.0

**Comment by mloubout** [comment]
Hi, the README may not be up to date, please refer to the correcponding script `examples/scripts/fwi_example/minConf.jl`

**Comment by kerim371** [comment]
@mloubout well there you mentionned the path: `examples/scripts/fwi_example/` but I can only see the path `examples/scripts/` like in the picture below. I use tag `v2.2.0`
If I we are talking about the same thing then there are also some other examples that are broken (as I think). You can try my colab notebook to launch them on the cloud (for now I work only with `scripts` examples).
![image](https://user-images.githubusercontent.com/43808863/101992419-2364d780-3cc4-11eb-94a0-4b2b6de27589.png)

**Comment by mloubout** [comment]
> there are also some other examples that are broken 

 Could you precise which examples are broken?

For the path, was a (fixed) typo to the file `examples/scripts/fwi_example_minConf.jl` that you can see on your screenshot.

**Comment by kerim371** [comment]
@mloubout I have not tried all of them yet but here are some:

- fwi_example_2D.jl: BoundsError: attempt to access 401×121 Array{Float32,2} at index [402, 1]

![image](https://user-images.githubusercontent.com/43808863/101995236-a2183f80-3cd9-11eb-8f1b-84e91ec3dfee.png)

- fwi_example_constraints.jl: BoundsError: attempt to access 401×121 Array{Float32,2} at index [402, 1]

![image](https://user-images.githubusercontent.com/43808863/101995189-62e9ee80-3cd9-11eb-8c4c-34030713c4db.png)

- fwi_example_minConf.jl: MethodError: no method matching minConf_SPG(::typeof(objective_function), ::PhysicalParameter{Float32}, ::typeof(ProjBound), ::JUDI.SLIM_optim.SPG_params). Closest candidates are:  minConf_SPG(::Any, !Matched::Array{vDt,N} where N, ::Any, ::Any) where vDt at /root/.julia/dev/JUDI/src/Optimization/SPGSlim.jl:78

**There were also some warnings like:** 
┌ Warning: Fixed length trace flag set in stream: IOBuffer(data=UInt8[...], readable=true, writable=false, seekable=true, append=false, size=7076688, maxsize=Inf, ptr=3601, mark=-1)
└ @ SegyIO /root/.julia/packages/SegyIO/uw4ZW/src/read/read_file.jl:26
judiVector{Float32}("Seismic data vector", 8016, 1, 16, GeometryIC(Any[400.0f0, 1013.333f0, 1626.667f0, 2240.0f0, 2853.333f0, 3466.666f0, 4080.0f0, 4693.334f0, 5306.666f0, 5920.0f0, 6533.334f0, 7146.666f0, 7760.0f0, 8373.333f0, 8986.667f0, 9600.0f0], Any[0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0, 0.0f0], Any[50.0f0, 50.0f0, 50.0f0, 50.0f0, 50.0f0, 50.0f0, 50.0f0, 50.0f0, 50.0f0, 50.0f0, 50.0f0, 50.0f0, 50.0f0, 50.0f0, 50.0f0, 50.0f0], Any[4.0f0, 4.0f0, 4.0f0, 4.0f0, 4.0f0, 4.0f0, 4.0f0, 4.0f0, 4.0f0, 4.0f0, 4.0f0, 4.0f0, 4.0f0, 4.0f0, 4.0f0, 4.0f0], Any[501, 501, 501, 501, 501, 501, 501, 501, 501, 501, 501, 501, 501, 501, 501, 501], Any[2000.0f0, 2000.0f0, 2000.0f0, 2000.0f0, 2000.0f0, 2000.0f0, 2000.0f0, 2000.0f0, 2000.0f0, 2000.0f0, 2000.0f0, 2000.0f0, 2000.0f0, 2000.0f0, 2000.0f0, 2000.0f0]), Array[Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0], Float32[-0.00096925104; -0.0016848503; … ; -0.0; -0.0]])

**or like:**
┌ Info: Precompiling PyPlot [d330b81b-6aea-500a-939a-2ce795aea3ee]
└ @ Base loading.jl:1278
WARNING: using PyPlot.plt in module Main conflicts with an existing identifier.
Info(12000, 1, Any[2646])

Also there were some other examples that were broken but I need to rerun them as I don't remember them and didn't save them.

**But there were some successful ones like:**

- extended_source_lsqr.jl
- fwi_gauss_newton.jl
- modeling_basic_2D.jl

**Comment by kerim371** [comment]
@mloubout I tested all script examples and saved the notebook with all the output errors in [repo](https://github.com/kerim371/Julia-Devito-Inversion-JUDI-examples-in-Colab)

**Comment by mloubout** [comment]
I will double check the examples, thanks for letting us know, I hope you can still use JUDI for what you need.

**Comment by mloubout** [comment]
#46 Should fix the issues with the examples

**Comment by kerim371** [comment]
@mloubout thank you for your work

I just tried the `exam` branch with all the fixed examples and seems to me that only one of them began to work correct: **fwi_example_minConf.jl**
![image](https://user-images.githubusercontent.com/43808863/102027112-24286700-3db3-11eb-8e98-ce8d7114a1c0.png)

I think the errors the same. I saved the notebook with all the output.

**Comment by mloubout** [comment]
Hum ok that's odd worked fine when I tried ill double check, thanks for trying it.

**Comment by mloubout** [comment]
I looked at your notebook and error message

```
 [21] (::JUDI.SLIM_optim.var"#objective#13"{Model,judiVector{Float32},judiVector{Float32},typeof(proj)})(::Float32, ::PhysicalParameter{Float32}) at /root/.julia/dev/JUDI/src/Optimization/fwi_linesearch.jl:8
```

So you have two installations:
- `/content/JUDI.j` that has the `exam` branch checked out
- ` /root/.julia/dev/JUDI` that is the one actually run and I'm not sure which version this is

So it may be that you are not running the `exam` branch

**Comment by kerim371** [comment]
I'm sorry, you are right...
I'm trying to fix that

**Comment by kerim371** [comment]
@mloubout the calculations just finished.

**Successful script examples:**

- extended_source_lsqr.jl
- fwi_example_2D.jl
- fwi_example_NLopt.jl
- fwi_example_minConf.jl
- modeling_basic_2D.jl
- modeling_extended_source_2D.jl
- modeling_extended_source_3D.jl
- modeling_wavefields_2D.jl

**Broken script examples:**

- fwi_example_constraints.jl
- fwi_gauss_newton.jl
- modeling_basic_3D.jl
- modeling_medical_2D.jl

I saved notebook with outputs. You can see the errors there

**Comment by mloubout** [comment]
Ok, pushed an update all examples should run now.

**Comment by kerim371** [comment]
@mloubout thank you,

I just ran the examples and now fails only `fwi_gauss_newton.jl`. The error says:
MethodError: no method matching median(::Array{Float32,2}, ::Int64)
Closest candidates are:
**median(::AbstractArray; dims) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Statistics/src/Statistics.jl:852
median(::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Statistics/src/Statistics.jl:836**

The notebook with outputs is saved

**Comment by mloubout** [comment]
Should be fixed now, looks like Statistics had change their syntax.

**Comment by kerim371** [comment]
@mloubout thank you very much
Now all examples work

Output from Gauss-Newton:
![image](https://user-images.githubusercontent.com/43808863/102259714-82bf2380-3f20-11eb-8a75-2fa62a356c07.png)
