### ISSUE TITLE
overload DepthScaling and Topmute operators for PhysicalParameter?

### ISSUE THREAD

**Issue by ziyiyin97** [slimgroup/JUDI.jl#48]
Would it make sense to overload depth scaling and top mute operators? Now the default operation of depth scaling on physical parameter is given in `https://github.com/slimgroup/JUDI.jl/blob/f22170d3709bf9f4320190b6915d063570c7e003/src/TimeModeling/ModelStructure.jl#L216` where it directly outputs Julia array. So I guess we can define the operation of depth scaling directly on physical parameters, then follow what we've done for judiWeights `https://github.com/slimgroup/JUDI.jl/blob/f22170d3709bf9f4320190b6915d063570c7e003/src/TimeModeling/judiWeights.jl#L203` so that it remains the data structure instead of outputting Julia arrays.

**Comment by mloubout** [comment]
Don't quote urls or it doesn't render.

Not sure about it, ideally I'd prefer JOLI to work on AbstractVectors, and bot depth scaling and topmute have to be removed from JUDI and put into the preconditionners.
