### ISSUE TITLE
JUDI.SLIM_optim

### ISSUE THREAD

**Issue by LeeyMessi** [slimgroup/JUDI.jl#6]
I have installed JUDI, unfortunately,terminal shows that "UnderVarError: SLIM_optim not defined" after running, I don't known what happen? please help me,,thank you !

**Comment by philippwitte** [comment]
SLIM_optium is part of JUDI and should have been automatically installed with the rest of the package. Are you also getting an error from `using JUDI.TimeModeling` or when you run any of the modeling examples such as `modeling_basic_2D.jl`?

**Comment by mloubout** [comment]
Two questions:
- Can you tell how you installed JUDI.
- Start julia and only run `using JUDI.SLIM_optim` and please paste here the error message

**Comment by LeeyMessi** [comment]
1. Pkg.clone("https://github.com/slimgroup/JUDI.jl")
2. Pkg.build("JUDI")
3. ENV["PYTHON"] = "./anaconda3/envs/devito/bin/python"
4. using JUDI.SLIM_optim
ERROR: UnderfVarError: SLIM_optim not defined

**Comment by henryk-modzelewski** [comment]
Try: 1) to skip 3rd step from above list in Julia, 2) import conda environment (devito judging by the path) before starting Julia, and 3) set PYTHON environment before you start Julia. Also, make sure that you installed devito in conda's devito environment. Let's see if it helps.

**Comment by LeeyMessi** [comment]
I am using Ubuntu,terminal shows that <"/home/lee/.julia/v0.6/JUDI"> after running:Pkg.dir("JUDI")

**Comment by LeeyMessi** [comment]
It is noteworthy that terminal shows “Info: No system-wide Python was found ;got the following error:...” after running :Pkg.build("PyCall")

**Comment by mloubout** [comment]
`ENV["PYTHON"] = "./anaconda3/envs/devito/bin/python"`

I think you need to set the absolute path not the relative path ie on my system
'home/usr/pathtopython`

you also need to set `ENV["PYTHON"]` before `pkg.clone` and you shouldn't need `pkg.build` as clone will do it.

**Comment by LeeyMessi** [comment]
Thank you very much. With your help, I have solved my problem.
