### ISSUE TITLE
marmousi_2D

### ISSUE THREAD

**Issue by LeeyMessi** [slimgroup/JUDI.jl#7]
Could you offer marmousi_2D model to me? 
run(`wget ftp://slim.eos.ubc.ca/data/SoftwareRelease/Imaging.jl/2DLSRTM/marmousi_2D.segy`)
run(`wgetftp://slim.eos.ubc.ca/data/SoftwareRelease/Imaging.jl/2DLSRTM/marmousi_migration_velocity.h5`)
these address I can't open them,  my email:leeyangmessi@163.com

**Comment by henryk-modzelewski** [comment]
The ftp server serves those files, so there is a problem with the way you download them. Try
  wget ftp://slim.eos.ubc.ca/data/SoftwareRelease/Imaging.jl/2DLSRTM/marmousi_2D.segy
  wget ftp://slim.eos.ubc.ca/data/SoftwareRelease/Imaging.jl/2DLSRTM/marmousi_migration_velocity.h5
directly in terminal rather then in Julia. The syntax of the commands in your post does not look right.

**Comment by LeeyMessi** [comment]
Thank you very much!
