### ISSUE TITLE
miniConf Library

### ISSUE THREAD

**Issue by seaninho94** [slimgroup/JUDI.jl#72]
I was trying to implement the example with the Overthrust model and everything is working well until the last line of code, where I need to use the miniConf_SPG library. This gives me an error, it seems like it can't find this library. How can I fix this? Am I missing something?

Thank you for your help!

**Comment by mloubout** [comment]
This submodule has been deprecated in favor of `SlimOptim.jl`. See for example
https://github.com/slimgroup/JUDI.jl/blob/master/examples/scripts/fwi_example_minConf.jl
