### ISSUE TITLE
Run JUDI with the newest version Devito-3.4

### ISSUE THREAD

**Issue by UHXinyan** [slimgroup/JUDI.jl#8]
Hi, I have updated the Devito recently from version 3.2 to the most recent version 3.4. But then I cannot run JUDI any more. It used to work well. When I tried to run `using JUDI.TimeModeling`, it shows the `ERROR: LoadError: PyError (PyImport_ImportModule)`. I wonder that is it caused by the Devito version upgrade? May I have any suggestions on what should I do? Thanks a lot!
![judi_runerror](https://user-images.githubusercontent.com/34178648/52889466-a6a75780-3145-11e9-8f0c-7065123a8156.jpg)

**Comment by philippwitte** [comment]
Hi, thank you for interest in our software! Currently, JUDI only supports Devito 3.2.0, but I can update it so that it works with the newest Devito. I will do this as soon as possible (within the next couple of days).
Regards,
Philipp

**Comment by UHXinyan** [comment]
Thank you so much! Looking forward in the updated JUDI! Many many Thanks!
Best regards,
Xinyan
