### ISSUE TITLE
MFE:  JUDI's boundary function fails in test_adjoint_J from Devito

### ISSUE THREAD

**Issue by nogueirapeterson** [slimgroup/JUDI.jl#99]
This MFE is related with PR #95 .
I could notice that the boundary from JUDI fails in `test_adjoint_J` in Devito. 
I only brought the initialize_damp from JUDI to Devito and ran the test. 
We create a MFE [mfe.txt](https://github.com/slimgroup/JUDI.jl/files/8227618/mfe.txt) to show that issue.
You can run the MFE as:
`python mfe.py -d devito`  
to run the `test_adjoint_J` with initialize_damp from Devito.
And
`python mfe.py -d judi` 
to run the `test_adjoint_J` with initialize_damp from JUDI.

So considering this fact, could we create a damp_kernel so that we could keep the two functions? I suggest this because I would like to have the viscoacoustic operators pass the tests like in Devito.

**Comment by mloubout** [comment]
All the operators including J pass the adjoint test in JUDI test suite so I don't think external tests are necessarily relevant.

I'll have a quick look though, by how much does it fail

**Comment by mloubout** [comment]
After some thoughts, since you add Q in a much better way, the current implementation isn't really needed. So feel free to replace the current one with the "devito" one. I'll check on one of my PR still works for long modeling times

**Comment by nogueirapeterson** [comment]
thanks for considering this.
